### ISSUE TITLE
Some logs resulting in 404

### ISSUE THREAD

**Issue by Nomad7** [bananahampster/hampalyzer#33]
I seem to be getting 404 errors fairly regularly for the last week - here's one example:
[L0517050.log](https://github.com/bananahampster/hampalyzer/files/8710599/L0517050.log)
[L0517051.log](https://github.com/bananahampster/hampalyzer/files/8710600/L0517051.log)
http://app.hampalyzer.com/parsedlogs/hello?-2022-May-17-12-33 

(not sure if this is useful but blarghs seem to work fine for comparison:
http://www.blarghalyzer.com/parsedlogs/l0517050/
http://www.blarghalyzer.com/parsedlogs/l0517051/ )

**Comment by Nomad7** [comment]
Here's another example: http://app.hampalyzer.com/parsedlogs/hello?-2022-May-20-12-1
[helloschtop2v2r1.log](https://github.com/bananahampster/hampalyzer/files/8742404/helloschtop2v2r1.log)
[helloschtop2v2r2.log](https://github.com/bananahampster/hampalyzer/files/8742405/helloschtop2v2r2.log)
3

**Comment by LightTreason** [comment]
The issue was that nginx was decoding the %3F when it redirects to the path with a forward slash at the end.

Your original upload works fine with this URL:
http://app.hampalyzer.com/parsedlogs/hello%3F-2022-May-17-12-33/

This could have been fixed by just adding that forward slash in the links, but while looking at this I found that the '?' was causing problems on Windows because the file system doesn't support paths with question marks in them.

I updated it to add '/' to the paths to avoid the redirect entirely and then for Windows compat I replaced the ? with an underscore. So, fixed two different ways.

The new path it ends up in:
http://app.hampalyzer.com/parsedlogs/hello_-2022-May-17-12-33/
